CREATE DATABASE IF NOT EXISTS banking_system;
USE banking_system;


CREATE TABLE IF NOT EXISTS accounts (
  acc_no BIGINT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  pin INT NOT NULL,
  balance BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  acc_no BIGINT NOT NULL,
  type ENUM('DEPOSIT','WITHDRAW') NOT NULL,
  amount BIGINT NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (acc_no) REFERENCES accounts(acc_no) ON DELETE CASCADE
);

SELECT * FROM accounts;
SELECT * FROM transactions;
SHOW DATABASES;

